// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	comment "dous/biz/router/comment"
	favorite "dous/biz/router/favorite"
	feed "dous/biz/router/feed"
	list "dous/biz/router/list"
	user "dous/biz/router/user"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	comment.Register(r)

	favorite.Register(r)

	list.Register(r)

	feed.Register(r)

	user.Register(r)
}
